[project]
name='src'
version='0.1.0'
description = 'Mlops project for productionizing models'
authors=[{name = 'Muhammed Shibili', email="muhammedshibili688@gmail.com"}]

[tools.setuptools]
packages = {find = {}}

[tools.setuptools.dynamic]
dependencies = {file = "requirements.txt"}