name : Deploy docker application to EC2 instance

on:
  push:
    branches: [main]
    

jobs:
  Continous-Integration:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Tag and Push image to Amazon ECR
        id: build-image
        uses: aws-actions/amazon-ecr-login@v1
        with:
          context: .
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: SSH to EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
         IMAGE-TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE-TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE-TAG
          echo :: Set-output name-image:: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE-TAG

Continious-Deployment:
  needs: Continous-Integration
  runs-on: self-hosted
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Run Docker image to server users
      run: |
        docker run -d -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" -e AWS_DEFAULT_REGION="${{secrets.AWS_DEFAULT_REGION}}" -e MONGODB_URL="${{secrets.MONGODB_URL}}" -p 5000:5000"{{steps.login-ecr.outputs.registry}}"/"{{secrets.ECR_REPO}}":latest
